### ISSUE TITLE
Problem with complex pages

### ISSUE THREAD

**Issue by jamielob** [Telerik-Verified-Plugins/NativePageTransitions#125]
Hi @EddyVerbruggen - I'm seeing a problem on older Android devices when there is a lot of JS processing going on in the destination page.  

The current page flicks to the destination page without transition, and then animates the destination page in (further along with its rendering) over the top.  I've put together a slowed down video of how that looks (this is just a demo Meteor app with an over the top calculation on the demo page to slow everything down).

https://www.youtube.com/watch?v=y5SzBpR8ioY&feature=em-upload_owner

I get why it's slow to start the transition - I just don't understand why the destination page is showing before the transition happens.

In production this is effecting pages that have to fetch remote data from multiple sources on load.

**Comment by EddyVerbruggen** [comment]
Can you also share an app reprocing this so I can try and fix it? Thx

**Comment by jamielob** [comment]
@EddyVerbruggen - Demo repo is available here but it is a Meteor JS app:

https://github.com/jamielob/native-transitions/tree/ShowingBeforeTransition

The piece that breaks everything is doing a lot of processing on the destination page.  For example, in the above repo it is:

```
thisInterval = Meteor.setInterval(function() {
		if (counter > 300) Meteor.clearInterval(thisInterval);
	  	array.push(counter);
		Session.set('array', array);
	    counter++;
	}, 1);
```

Where I am displaying the value of the array in the page.

**Comment by jamielob** [comment]
@EddyVerbruggen - I've put together a simpler demo repo based off of your demo.

https://github.com/jamielob/npt-demo2

It shows slightly different symptoms (this one shows the current page again before transitioning to the new one) but it's similar.  To replicate here I've just used some complex CSS on the destination page.  Tested on an Android Moto G device.

**Comment by EddyVerbruggen** [comment]
Focussed on the second app - will check the first one soon as well.

**Comment by jamielob** [comment]
Thank you.  I've tried in my production app with a delay of 5000ms too.  It flicks to the destination page, then waits for 5 seconds, then transitions it over the top.

**Comment by jamielob** [comment]
It looks like any code that causes a delay before the native transitions code is called means that you see the destination page before the screenshot of the current page has completed.

**Comment by jamielob** [comment]
@EddyVerbruggen - The more I look into this, the more I think it's a problem with the way that I've implemented it in Meteor. I'm closing this for now and will come back if I find anything that needs sharing.

**Comment by insaneinc01** [comment]
Hello @jamielob, I've been battling the exact same issue on Android since a while, and I was pretty convinced it was a Meteor + Cordova issue. I tried all possible combinations now - using delay: -1 and executePendingTransition etc, but now I think its a problem with the plugin itself only on Android. Works beautifully on iOS. 
Did you finally solve this issue? Can you post some pointers please. I'm trying to make a video of the issue, will post it soon. Thanks.

**Comment by insaneinc01** [comment]
btw, I'm experiencing this in the Drawer navigation. The end state of the transition shows for a split second before the actual transition starts. 
No matter what the delay (50 or even 5000), the brief flicker of the completed state is always there before actual transition. Due to this the drawer navigation looks glitchy.

**Comment by insaneinc01** [comment]
@EddyVerbruggen @jamielob Please see this video 
Notice how the first time it animates very smoothly. 
From the second time onwards, there's a sudden flicker and then the animation kicks in.
https://drive.google.com/file/d/0Bwze-NVj3r8VMzdtaHhFdGVQZDg/view?usp=sharing

**Comment by insaneinc01** [comment]
@EddyVerbruggen  Any comment on this issue please? Really looking for a fix.. thank you.

**Comment by jamielob** [comment]
Hi @insaneinc01 - I don't think the problem I had was the same as yours.  Are you seeing the flicker with other animations other than drawer?  Are you using Crosswalk?

**Comment by insaneinc01** [comment]
Hello @jamielob The flicker happens only with the Drawer **open** animation. Drawer close has no problem!
I'm not using Crosswalk. 

This issue is exactly the same as what you mentioned, but for the Drawer animation -
  _"The current page flicks to the destination page without transition, and then animates the destination page in (further along with its rendering) over the top"_

 So for drawer-open animation, the **destination** is where the current screen is moved all the way to the right leaving only 15% (example) of it visible on the right edge. 

Here's what I think is happening:
1. Call drawer open method
2. Plugin takes a screenshot of the current screen
3. Destination (end state) of the transition is shown for a split second - so we quickly see the current screen jump to the right edge
4. The transition starts and smoothly moves the current screen to the right to its destination
5. While the new screen (drawer screen) is transitioned along into position.   

In the above sequence, **step 3** is the culprit. If step 3 can somehow be removed from the sequence, the issue is solved. 
I hope i was able to throw some light on the issue. 
Thanks

**Comment by jamielob** [comment]
FYI I haven't used the drawer animation myself.

Can you post the code that you're using?
