### ISSUE TITLE
Allows more than one transition at a time.

### ISSUE THREAD

**Issue by martinamw** [Telerik-Verified-Plugins/NativePageTransitions#137]
It is possible to implement 2 transitions if for example user double taps to initiate transition.  The screenshot taken will be part of the first transition - causing a ghost effect.
This could be fixed in JS, but would be better to fix on native side.  If in middle of transiton, don't allow anymore.  I am using 'executependingtransition'.

**Comment by EddyVerbruggen** [comment]
I appreciate the idea but imo this should be fixed in JS as I'd have to duplicate all that logic in various native codebases while it's a very simple check in JS.

If you feel like you're up to the task then go ahead and add a PR that adds this logic to [the JS bridge](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/www/NativePageTransitions.js), or otherwise keep the fix in your own JS code.
