### ISSUE TITLE
Thread Warning on iOS

### ISSUE THREAD

**Issue by ericalli** [Telerik-Verified-Plugins/NativePageTransitions#50]
In the debug console of Xcode, the following warnings appear when transitions are fired:
```
THREAD WARNING: ['NativePageTransitions'] took '97.010986' ms. Plugin should use a background thread.
```

Running iOS 8.3 and Xcode 6.3.1.

Not sure if this is of consequence, but it does seem to have some effect on performance.

Any thoughts on this?

**Comment by salilsethi** [comment]
I am getting the same error. Were you able to figure out what is going on here?

**Comment by gottib** [comment]
I am having the same error. Any news on this issue?

**Comment by EddyVerbruggen** [comment]
You don't need to worry about it. The thing is, Cordova shouts this in the log when a plugin is using the UI thread for more than X ms. With almost every other plugin this is relevant and I (and most other plugin authors) will use a background thread for longer computations (f.i. waiting for a remote server to respond). Otherwise the webview would be frozen until the plugin returns control.

This plugin however NEEDS to perform computations on the UI thread (creating a screenshot f.i.) which can't run on a background thread (a view can only be changed by the thread that created it).

So please ignore them ;)
