### ISSUE TITLE
Coradova5 can not compile

### ISSUE THREAD

**Issue by ctl1690** [Telerik-Verified-Plugins/NativePageTransitions#52]
as title
exception:

![2015-05-13 08 42 41](https://cloud.githubusercontent.com/assets/2221790/7601687/767e7992-f94c-11e4-8df4-833ebfb9b221.png)

**Comment by Honry** [comment]
I also experience this issue.

**Comment by EddyVerbruggen** [comment]
I'll take a look shortly, thanks for letting me know both!

**Comment by EddyVerbruggen** [comment]
Hi @Honry and @ctl1690, thanks for reporting this issue! I used the kind advice of @agrieve in #33 to make this compatible with the latest Cordova release, but I also needed some more magic trickery to make `#hash` navigation work again with the new way the Android part of this plugin is implemented (essentially the old way was no longer possible to major Cordova-Android surgery in order to support pluggable webviews).

Because of this big change I'm not tagging a release yet, but did push the code to the master branch. Please test it a bit and let me know if you run into any issues in your app(s).

Thanks in advance,
Eddy

**Comment by Honry** [comment]
hi, @EddyVerbruggen 
Thanks for your quick fix, it works now. And may I know what's your plan to push it to npm cordova plugin?

**Comment by EddyVerbruggen** [comment]
Awesome, thanks for the quick check!

I will definitely publish it to NPM but we're discussing the best approach. In the meanwhile I will test this a bit more (older devices etc) and publish an update [here](http://plugins.cordova.io/#/package/com.telerik.plugins.nativepagetransitions).

**Comment by ctl1690** [comment]
Thanks a lot. It work!!!

**Comment by EddyVerbruggen** [comment]
Thanks both! I've also verified it works still fine on older Android versions, so closing this and releasing a new version.
