### ISSUE TITLE
can't work well with crosswalk since crosswalk change the internal view for rendering web pages

### ISSUE THREAD

**Issue by vagrant1991** [Telerik-Verified-Plugins/NativePageTransitions#96]
in order to solve some bug caused by TexureView, crosswalk team has changed the internal view for rendering web page, now it's SurfaceView, so NativePageTransitions plugin can't work well with crosswalk.

ref:
https://crosswalk-project.org/apis/embeddingapidocs/reference/org/xwalk/core/XWalkView.html
https://crosswalk-project.org/jira/browse/XWALK-4738

**Comment by EddyVerbruggen** [comment]
So [this](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/android/NativePageTransitions.java#L652-L657) will no longer work for newer Crosswalk versions then. Do you have any idea how to grab a screenshot from SurfaceView?

Perhaps it's worth a shot trying [this solution](http://stackoverflow.com/questions/27817577/android-take-screenshot-of-surface-view-shows-black-screen), are you able to test that method?

**Comment by tbro028** [comment]
Any update on this, plans to move to SurfaceView or sticking with TextureView?

**Comment by EddyVerbruggen** [comment]
@tbro028 As soon as a reliable solution has been found to grab a screenshot from SurfaceView I will jump on it. Ideas?

**Comment by tbro028** [comment]
beyond my level sorry.

**Comment by vagrant1991** [comment]
@EddyVerbruggen  hi, i hava searched a lot and did some test,  these code work. this method can get the bitmap represents the SurfaceView. but it seems can't do webviewAnimation  on SurfaceView.  i am stuck here.                 

    private Bitmap getXwalkBitmap(ViewGroup group) {

        int childCount = group.getChildCount();
        for (int i = 0; i < childCount; i++) {
            View child = group.getChildAt(i);
            String parentClassName = child.getParent().getClass().toString();
            boolean isSurfaceView = parentClassName.contains("XWalk") && child instanceof SurfaceView;
            if (isSurfaceView) {
                SurfaceView surfaceView = ((SurfaceView) child);
                Bitmap bitmap = Bitmap.createBitmap(surfaceView.getWidth(), surfaceView.getHeight(), Bitmap.Config.ARGB_4444);
                Canvas c = new Canvas(bitmap);
                surfaceView.draw(c);
                return bitmap;
            } else if (parentClassName.contains("XWalk") && child instanceof TextureView) {
                Bitmap bitmap = ((TextureView) child).getBitmap();
                if (bitmap != null) {
                    return bitmap;
                }
            } else if (child instanceof ViewGroup) {
                Bitmap bitmap = getXwalkBitmap((ViewGroup) child);
                if (bitmap != null) {
                    return bitmap;
                }
            }
        }

        return null;
    }

**Comment by EddyVerbruggen** [comment]
@vagrant1991 Thanks for the attempted solution! I debugged your code and saw that the content of the bitmap is actually a fully transparent image. So that's why you don't see a transition.

You can inspect the content of that `bitmap` object at the `return bitmap` line above in your IDE (I used Android Studio), or by saving the bitmap to a file.

**Comment by roblav96** [comment]
Did you try this?
<preference name="CrosswalkAnimatable" value="true" />
https://github.com/gitawego/cordova-screenshot#known-issue

**Comment by EddyVerbruggen** [comment]
Not sure if that last comment was for me, but that `CrosswalkAnimatable` setting is also in [the official doc](http://plugins.telerik.com/cordova/plugin/native-page-transitions).

**Comment by roblav96** [comment]
Oh, sorry :X

**Comment by EddyVerbruggen** [comment]
Note to self: the screenshot plugin uses a new Crosswalk feature where you can ask it to capture and return a screenshot for you in an async way: https://github.com/gitawego/cordova-screenshot/blob/master/src/android/Screenshot.java

That looks promising for us as well, but it depends a bit on how fast snagging the screenshot is.

**Comment by EddyVerbruggen** [comment]
See [my last comment in 108](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/108#issuecomment-192931745) - using the approach of the screenshot plugin work for grabbing a screenshot, but it's just not possible to animate the SurfaceView.

There would be an awful hack which would never be perfect so I'm not going to do it: grab a screenshot, load the new page in the webview (hidden because of the screenshot), grab a second screenshot of the webview and use those screenshots to perform fi. a flip. After the transition hide both screenshots. This would be slower and (worse) if the webview state changes between the moment the second screenshot is grabbed and the screenshots are hidden you would see a sudden change of the webview content.
